language: node_js

node_js: 8

env:
  - NODE_ENV=ci

install:
  - npm ci
  - npm run bootstrap

script:
  - npm test
  - npm run build

deploy:
  - provider: script
    script: npm run deploy:staging
    skip_cleanup: true
    on:
      branch: master
  - provider: script
    script: npm run deploy:production
    skip_cleanup: true
    on:
      tags: true
      branch: master
