language: node_js

node_js: 8

env:
  - NODE_ENV=ci

install:
  - npm ci
  - npm run bootstrap

script:
  - npm test
  - npm run build

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN  # Set in the settings page of your repository, as a secure variable
  keep-history: true
  local-dir: dist
  on:
    branch: master
