language: node_js

node_js: 8

env:
  - NODE_ENV=ci

before_install:
  - openssl aes-256-cbc -K $encrypted_57f1913b149f_key -iv $encrypted_57f1913b149f_iv -in packages/frograming-web/.env.local.enc -out packages/frograming-web/.env.local -d

install:
  - npm ci
  - npm run bootstrap

script:
  - npm test
  - npm run build

deploy:
  - provider: script
    script: npm run deploy:staging
    skip_cleanup: true
    on:
      branch: master
  - provider: script
    script: npm run deploy:production
    skip_cleanup: true
    on:
      tags: true
      branch: master
